index:
    path: /
    controller: App\Controller\TasksController::indexAction
    methods: [GET]

destroy_task:
    path: /tasks/{id}
    controller: App\Controller\TasksController::destroyAction
    methods: [DELETE]

update_task:
    path: /tasks/{id}
    controller: App\Controller\TasksController::updateAction
    methods: [PATCH]

store_task:
    path: /tasks
    controller: App\Controller\TasksController::storeAction
    methods: [POST]

fetch_tasks:
    path: /api/tasks
    controller: App\Controller\Api\TasksController::index
