index:
    path: /
    controller: App\Controller\TasksController::index

edit_task:
    path: /{id}/edit
    controller: App\Controller\TasksController::edit

fetch_tasks:
    path: /api/tasks
    controller: App\Controller\Api\TasksController::index

update_task:
    path: /tasks/{id}
    controller: App\Controller\TasksController::update
