index:
    path: /
    controller: App\Controller\TasksController::index
    methods: [GET]

delete_task:
    path: /tasks/{id}
    controller: App\Controller\TasksController::destroy
    methods: [DELETE]

update_task:
    path: /tasks/{id}
    controller: App\Controller\TasksController::update
    methods: [PUT]

fetch_tasks:
    path: /api/tasks
    controller: App\Controller\Api\TasksController::index
